name: hsmproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  get: ^4.6.6
  image_picker: ^1.1.2
  firebase_storage: ^12.4.10
  permission_handler: ^12.0.1
  email_validator: ^3.0.0
  build_runner: ^2.4.6
  intl: ^0.19.0
  google_fonts: ^6.3.1
  uuid: ^4.5.1
  flutter_animate: ^4.5.2
  firebase_analytics: ^11.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true