// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARpeLLlrBjgih-2igj98PWmFLuHh8Dp_Q',
    appId: '1:1088320933384:web:738571c982e69554328bbd',
    messagingSenderId: '1088320933384',
    projectId: 'hmsproject-3d705',
    authDomain: 'hmsproject-3d705.firebaseapp.com',
    storageBucket: 'hmsproject-3d705.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDrPXn_7KXSRV8QJK5FFWXVf7CbIN_EZs',
    appId: '1:1088320933384:android:a2e3cc1a504e6b0e328bbd',
    messagingSenderId: '1088320933384',
    projectId: 'hmsproject-3d705',
    storageBucket: 'hmsproject-3d705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPPsS2SH-XOOFeBWZp17apxTw1RX14pc8',
    appId: '1:1088320933384:ios:6639f5f66e72db75328bbd',
    messagingSenderId: '1088320933384',
    projectId: 'hmsproject-3d705',
    storageBucket: 'hmsproject-3d705.firebasestorage.app',
    iosBundleId: 'com.example.hsmproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPPsS2SH-XOOFeBWZp17apxTw1RX14pc8',
    appId: '1:1088320933384:ios:6639f5f66e72db75328bbd',
    messagingSenderId: '1088320933384',
    projectId: 'hmsproject-3d705',
    storageBucket: 'hmsproject-3d705.firebasestorage.app',
    iosBundleId: 'com.example.hsmproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARpeLLlrBjgih-2igj98PWmFLuHh8Dp_Q',
    appId: '1:1088320933384:web:c101462c361c4edf328bbd',
    messagingSenderId: '1088320933384',
    projectId: 'hmsproject-3d705',
    authDomain: 'hmsproject-3d705.firebaseapp.com',
    storageBucket: 'hmsproject-3d705.firebasestorage.app',
  );
}
